# Generated by Django 5.1 on 2024-08-20 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_customuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
