# Generated by Django 5.1 on 2024-09-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
