# Generated by Django 5.1 on 2024-09-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
